import { cssVar } from '@toeverything/theme';
import { createGlobalTheme, globalStyle } from '@vanilla-extract/css';

import {
  cadence,
  CADENCE_DEFAULT_CHROMA,
  CADENCE_DEFAULT_HUE,
  cadenceSeed,
  motion,
} from './tokens.css';

const sansFamily =
  "'Google Sans', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Noto Color Emoji'";

globalStyle(':root', {
  vars: {
    '--affine-font-family': sansFamily,
    '--affine-font-sans-family': sansFamily,
  },
  fontOpticalSizing: 'auto',
});

// Build an OKLCH color from the accent seed. `lightness` and `chroma` are the
// role's fixed tone and saturation; the seed supplies the hue and scales the
// saturation, so contrast between roles holds for any accent.
const tone = (lightness: number, chroma: number, hueShift = 0) =>
  `oklch(${lightness} calc(${chroma} * var(${cadenceSeed.chroma})) calc(var(${cadenceSeed.hue}) + ${hueShift}))`;

// Tertiary sits a sixth of the wheel away so playful accents never clash with
// primary.
const TERTIARY_SHIFT = 60;

globalStyle(':root', {
  vars: {
    [cadenceSeed.hue]: String(CADENCE_DEFAULT_HUE),
    [cadenceSeed.chroma]: String(CADENCE_DEFAULT_CHROMA),
  },
});

createGlobalTheme(':root, [data-theme="light"]', cadence, {
  primary: tone(0.48, 0.13),
  onPrimary: '#ffffff',
  primaryContainer: tone(0.92, 0.05),
  onPrimaryContainer: tone(0.33, 0.1),
  tertiary: tone(0.5, 0.12, TERTIARY_SHIFT),
  tertiaryContainer: tone(0.93, 0.05, TERTIARY_SHIFT),
  onTertiaryContainer: tone(0.33, 0.09, TERTIARY_SHIFT),
  frame: tone(0.94, 0.028),
  frameSelected: 'rgba(255, 255, 255, 0.82)',
  surfaceContainer: tone(0.965, 0.008),
  surfaceContainerHigh: tone(0.93, 0.014),
  outline: tone(0.58, 0.02),
  outlineVariant: tone(0.86, 0.016),
});

createGlobalTheme('[data-theme="dark"]', cadence, {
  primary: tone(0.82, 0.09),
  onPrimary: tone(0.3, 0.08),
  primaryContainer: tone(0.4, 0.08),
  onPrimaryContainer: tone(0.92, 0.05),
  tertiary: tone(0.82, 0.09, TERTIARY_SHIFT),
  tertiaryContainer: tone(0.4, 0.07, TERTIARY_SHIFT),
  onTertiaryContainer: tone(0.93, 0.05, TERTIARY_SHIFT),
  frame: tone(0.215, 0.04),
  frameSelected: tone(0.33, 0.06),
  surfaceContainer: tone(0.235, 0.01),
  surfaceContainerHigh: tone(0.295, 0.014),
  outline: tone(0.66, 0.02),
  outlineVariant: tone(0.36, 0.016),
});

// Generated by sampling a damped spring (mass 1) until it settles within 0.2%.
// Comments give stiffness and damping ratio.
createGlobalTheme(':root', motion, {
  // 1400, 0.6
  spatialFast: {
    duration: '270ms',
    easing:
      'linear(0, 0.074, 0.246, 0.453, 0.653, 0.821, 0.947, 1.03, 1.076, 1.094, 1.091, 1.077, 1.058, 1.039, 1.022, 1.008, 0.999, 0.994, 0.991, 0.991, 0.992, 0.994, 0.996, 0.997, 1)',
  },
  // 700, 0.7
  spatialDefault: {
    duration: '350ms',
    easing:
      'linear(0, 0.062, 0.205, 0.378, 0.55, 0.701, 0.823, 0.914, 0.977, 1.016, 1.037, 1.045, 1.045, 1.039, 1.032, 1.024, 1.016, 1.01, 1.005, 1.002, 1, 0.999, 0.998, 0.998, 1)',
  },
  // 300, 0.8
  spatialSlow: {
    duration: '470ms',
    easing:
      'linear(0, 0.048, 0.16, 0.298, 0.441, 0.573, 0.687, 0.781, 0.855, 0.91, 0.951, 0.978, 0.996, 1.007, 1.013, 1.015, 1.015, 1.014, 1.012, 1.009, 1.007, 1.005, 1.004, 1.003, 1)',
  },
  // 3800, 1
  effectsFast: {
    duration: '140ms',
    easing:
      'linear(0, 0.051, 0.162, 0.293, 0.421, 0.537, 0.635, 0.716, 0.782, 0.833, 0.874, 0.905, 0.929, 0.947, 0.961, 0.971, 0.979, 0.984, 0.988, 0.992, 0.994, 0.996, 0.997, 0.998, 1)',
  },
  // 1600, 1
  effectsDefault: {
    duration: '220ms',
    easing:
      'linear(0, 0.053, 0.167, 0.301, 0.431, 0.547, 0.645, 0.726, 0.791, 0.841, 0.881, 0.911, 0.934, 0.951, 0.964, 0.973, 0.981, 0.986, 0.99, 0.992, 0.995, 0.996, 0.997, 0.998, 1)',
  },
  // 800, 1
  effectsSlow: {
    duration: '300ms',
    easing:
      'linear(0, 0.05, 0.158, 0.287, 0.413, 0.528, 0.626, 0.708, 0.774, 0.826, 0.868, 0.9, 0.925, 0.944, 0.958, 0.969, 0.977, 0.983, 0.987, 0.991, 0.993, 0.995, 0.996, 0.997, 1)',
  },
});

// Reduced motion keeps color fades and drops everything that moves.
globalStyle(':root', {
  '@media': {
    '(prefers-reduced-motion: reduce)': {
      vars: {
        [motion.spatialFast.duration]: '0ms',
        [motion.spatialDefault.duration]: '0ms',
        [motion.spatialSlow.duration]: '0ms',
      },
    },
  },
});

globalStyle('body', {
  color: cssVar('textPrimaryColor'),
  fontFamily: cssVar('fontFamily'),
  fontSize: cssVar('fontBase'),
});
